# Generated by Django 4.2.3 on 2023-07-26 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('open_for', models.CharField(choices=[('ST', 'Study Partners'), ('PP', 'Pair Programming Partners'), ('CR', 'Code Reviewers'), ('CT', 'Contributors')], default='CT', max_length=2)),
                ('time_estimate', models.CharField(choices=[('DY', 'Days'), ('WK', 'Weeks'), ('MT', 'Months'), ('YR', 'Years')], default='DY', max_length=2)),
                ('repo_url', models.URLField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated'],
                'indexes': [models.Index(fields=['-updated'], name='projects_pr_updated_31ae12_idx')],
            },
        ),
    ]
